### 1. Autenticación: Login de Usuario
POST http://localhost:5001/login
Content-Type: application/json

{
  "username": "Cesar Espinola",
  "pin": "2701"
}

### 2. Consulta de Saldo
GET http://localhost:5002/saldo
Authorization: Bearer {{token}}

### 3. Operación de Retiro de Fondos
POST http://localhost:5002/retiro
Authorization: Bearer {{token}}
Content-Type: application/json

{
  "monto": 500000
}

### 4. Operación de Transferencia Intercuentas
POST http://localhost:5002/transferir
Authorization: Bearer {{token}}
Content-Type: application/json

{
  "receptor_id": 2,
  "monto": 100000
}

### 5. Auditoría: Consulta General de Logs
GET http://localhost:5000/logs
Authorization: Token TOKEN-ADMIN-005

### 6. Auditoría: Consulta Filtrada por Servicio y Severidad
GET http://localhost:5000/logs?service=atm-auth-service&severity=INFO
Authorization: Token TOKEN-ADMIN-005

### 7. Auditoría: Métricas y Estadísticas Agregadas
GET http://localhost:5000/stats
Authorization: Token TOKEN-ADMIN-005